### ISSUE TITLE
No i2c communication with Adafruit Feather Board

### ISSUE THREAD

**Issue by b-nathan** [sparkfun/SparkFun_LSM303C_6_DOF_IMU_Breakout_Arduino_Library#1]
When I run one of the example for adafruit feather board esp32 then nothing happen on the i2c lines. 
I looked through the code (i'm working with visual micro) I couldn't find any differences to the example for RTC pcf8523, wich works perfectly.

Is this library not made for other boards?
I'm looking hard for a library for the lsm303c. This is the only one I could find.
Thanks for any help.

**Comment by bboyho** [comment]
Hi,

I'm sorry for the delay in the reply. I was closing another issue when I noticed your question. Try redownloading the latest library. Previously, the Wire.begin() was in the .cpp file causing it to reset the bus. I remember seeing this in another issue. I do not have a Feather Board with ESP32 to verify. By moving the Wire.begin() into the setup, it fixed some of the issues that I saw in another library.

I'll close this issue for now but if you still have problems, we can re-open this issue.
